name: practica3
description: Aplicación multimedia con cámara, audio y galería
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Gestión de estado
  provider: ^6.1.2

  # Cámara y medios
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  gal: ^2.3.2
  photo_manager: ^3.0.0

  # Audio - GRABACIÓN (versión fija para compatibilidad)
  record: 5.1.2

  # Audio - REPRODUCCIÓN
  audioplayers: ^6.1.0

  # Conversión de audio
  ffmpeg_kit_flutter: ^6.0.3

  # Procesamiento de imágenes
  image: ^4.1.7
  exif: ^3.3.0

  # Base de datos local
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0

  # Permisos
  permission_handler: ^11.4.0

  # UI y utilidades
  intl: ^0.19.0
  shared_preferences: ^2.2.2

  # Compartir archivos
  share_plus: ^7.2.2

  # Iconos
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# Forzar versiones compatibles
dependency_overrides:
  record_linux: 1.2.1
  record_platform_interface: 1.4.0

flutter:
  uses-material-design: true